In [2]:
import pandas as pd
import numpy as np
import os

In [5]:

new_cars = pd.read_csv(r"data\raw\hatla2ee_new_cars.csv")
used_cars = pd.read_csv(r"data\raw\hatla2ee_used_cars.csv")

df = pd.concat([new_cars, used_cars], ignore_index=True)

In [6]:
print(df.shape)
df.head()

(12681, 14)

,page,car_type,car_name,year,mileage,transmission,fuel,price,location,brand,model,car_url,image_url,scraped_at
0,1,new,Kia K3 2025,2025,0 KM,Automatic,Gas,"1,320,000 EGP",NaN,Kia,K3,https://eg.hatla2ee.com/en/new-car/kia/K3/unit...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:20:29
1,1,new,Hyundai Elantra 2025,2025,0 KM,Automatic,Gas,"1,340,000 EGP",NaN,Hyundai,Elantra,https://eg.hatla2ee.com/en/new-car/hyundai/ela...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:20:30
2,1,new,Byd Qin 2025,2025,0 KM,Automatic,Hybrid,"1,200,000 EGP",NaN,Byd,Qin,https://eg.hatla2ee.com/en/new-car/byd/Qin/uni...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:20:31
3,1,new,Hyundai Santa Fe 2025,2025,0 KM,Automatic,Hybrid,"3,495,000 EGP",NaN,Hyundai,Santa Fe,https://eg.hatla2ee.com/en/new-car/hyundai/san...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:20:31
4,1,new,MG HS 2026,2026,0 KM,Automatic,Gas,"1,750,000 EGP",NaN,MG,HS,https://eg.hatla2ee.com/en/new-car/moris-garag...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:20:33

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12681 entries, 0 to 12680
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   page          12681 non-null  int64
 1   car_type      12681 non-null  object
 2   car_name      12681 non-null  object
 3   year          12681 non-null  int64
 4   mileage       12681 non-null  object
 5   transmission  12681 non-null  object
 6   fuel          12681 non-null  object
 7   price         12681 non-null  object
 8   location      10173 non-null  object
 9   brand         12681 non-null  object
 10  model         12679 non-null  object
 11  car_url       12681 non-null  object
 12  image_url     12681 non-null  object
 13  scraped_at    12681 non-null  object
dtypes: int64(2), object(12)
memory usage: 1.4+ MB

In [8]:
df.isnull().sum()

page               0
car_type           0
car_name           0
year               0
mileage            0
transmission       0
fuel               0
price              0
location        2508
brand              0
model              2
car_url            0
image_url          0
scraped_at         0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df["car_url"].duplicated().sum()

82

In [12]:
df[df["car_url"].duplicated()]

,page,car_type,car_name,year,mileage,transmission,fuel,price,location,brand,model,car_url,image_url,scraped_at
60,6,new,Kaiyi X3 Pro 2026,2026,0 KM,Automatic,Gas,"960,000 EGP",NaN,Kaiyi,X3 Pro,https://eg.hatla2ee.com/en/new-car/Kaiyi/KAIYI...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:22:27
255,21,new,Soueast S 06 2027,2027,0 KM,Automatic,Gas,"1,555,000 EGP",NaN,Soueast,S 06,https://eg.hatla2ee.com/en/new-car/soueast/S+0...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:28:10
699,57,new,MG GT 2026,2026,0 KM,Automatic,Gas,"1,405,000 EGP",NaN,MG,GT,https://eg.hatla2ee.com/en/new-car/moris-garag...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:41:06
758,62,new,Mercedes CLA 200 2026,2026,0 KM,Automatic,Gas,"4,050,000 EGP",NaN,Mercedes,CLA 200,https://eg.hatla2ee.com/en/new-car/mercedes/cl...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:42:52
781,65,new,Nissan Juke 2026,2026,0 KM,Automatic,Gas,"1,100,000 EGP",NaN,Nissan,Juke,https://eg.hatla2ee.com/en/new-car/nissan/juke...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:43:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11736,502,used,Mitsubishi Lancer Puma 2004,2004,"271,000 KM",Automatic,Gas,"400,000 EGP","Hadayek October, Giza",Mitsubishi,Lancer Puma,https://eg.hatla2ee.com/en/car/mitsubishi/Lanc...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 16:54:18
11772,504,used,Kia Sportage 2020,2020,"160,000 KM",Automatic,Gas,"1,200,000 EGP",Suez,Kia,Sportage,https://eg.hatla2ee.com/en/car/kia/sportage/71...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 16:55:03
11927,512,used,Hyundai Verna 2016,2016,"202,000 KM",Manual,Gas,"410,000 EGP","Mansoura, Dakahlia",Hyundai,Verna,https://eg.hatla2ee.com/en/car/hyundai/verna/7...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 16:57:19
12006,516,used,Mahindra Scorpio 2008,2008,"260,000 KM",Manual,Diesel,"260,000 EGP",Cairo,Mahindra,Scorpio,https://eg.hatla2ee.com/en/car/mahindra/scorpi...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 16:58:30
12467,540,used,Geely Emgrand X7 2015,2015,"350,000 KM",Manual,Gas,"320,000 EGP",Giza,Geely,Emgrand X7,https://eg.hatla2ee.com/en/car/geely/emgrand-x...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 17:06:02

In [ ]:
df[(df["car_url"].duplicated()) &
    (df["location"].isna()) &
    (df["mileage"].str.upper() == "0 KM")
  ]

,page,car_type,car_name,year,mileage,transmission,fuel,price,location,brand,model,car_url,image_url,scraped_at
60,6,new,Kaiyi X3 Pro 2026,2026,0 KM,Automatic,Gas,"960,000 EGP",NaN,Kaiyi,X3 Pro,https://eg.hatla2ee.com/en/new-car/Kaiyi/KAIYI...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:22:27
255,21,new,Soueast S 06 2027,2027,0 KM,Automatic,Gas,"1,555,000 EGP",NaN,Soueast,S 06,https://eg.hatla2ee.com/en/new-car/soueast/S+0...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:28:10
699,57,new,MG GT 2026,2026,0 KM,Automatic,Gas,"1,405,000 EGP",NaN,MG,GT,https://eg.hatla2ee.com/en/new-car/moris-garag...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:41:06
758,62,new,Mercedes CLA 200 2026,2026,0 KM,Automatic,Gas,"4,050,000 EGP",NaN,Mercedes,CLA 200,https://eg.hatla2ee.com/en/new-car/mercedes/cl...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:42:52
781,65,new,Nissan Juke 2026,2026,0 KM,Automatic,Gas,"1,100,000 EGP",NaN,Nissan,Juke,https://eg.hatla2ee.com/en/new-car/nissan/juke...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:43:52
802,67,new,Mercedes C 200 2025,2025,0 KM,Automatic,Gas,"3,300,000 EGP",NaN,Mercedes,C 200,https://eg.hatla2ee.com/en/new-car/mercedes/c-...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:44:33
823,69,new,Mercedes E 200 2026,2026,0 KM,Automatic,Gas,"6,000,000 EGP",NaN,Mercedes,E 200,https://eg.hatla2ee.com/en/new-car/mercedes/e-...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:45:13
868,75,new,MG 5 2026,2026,0 KM,Automatic,Gas,"1,100,000 EGP",NaN,MG,5,https://eg.hatla2ee.com/en/new-car/moris-garag...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:47:28
924,81,new,Mercedes GLC 300 2026,2026,0 KM,Automatic,Gas,"5,850,000 EGP",NaN,Mercedes,GLC 300,https://eg.hatla2ee.com/en/new-car/mercedes/gl...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:49:35
936,82,new,Mercedes Viano 2026,2026,0 KM,Automatic,Gas,"6,650,000 EGP",NaN,Mercedes,Viano,https://eg.hatla2ee.com/en/new-car/mercedes/Vi...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 14:49:58
1305,135,new,Avatr 12 2026,2026,0 KM,Automatic,Electric,"3,350,000 EGP",NaN,Avatr,12,https://eg.hatla2ee.com/en/new-car/avatr/avatr...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:06:24
1334,139,new,Mercedes CLA 200 2026,2026,0 KM,Automatic,Gas,"3,850,000 EGP",NaN,Mercedes,CLA 200,https://eg.hatla2ee.com/en/new-car/mercedes/cl...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:07:41
1337,140,new,Byd Leopard 5 2025,2025,0 KM,Automatic,Hybrid,"3,100,000 EGP",NaN,Byd,Leopard 5,https://eg.hatla2ee.com/en/new-car/byd/Byd_Leo...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:07:52
1589,189,new,Cadillac Escalade 2025,2025,0 KM,Automatic,Gas,"14,500,000 EGP",NaN,Cadillac,Escalade,https://eg.hatla2ee.com/en/new-car/cadillac/es...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:23:15
1712,214,new,Mercedes CLA 200 2025,2025,0 KM,Automatic,Gas,"3,250,000 EGP",NaN,Mercedes,CLA 200,https://eg.hatla2ee.com/en/new-car/mercedes/cl...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:30:28
1758,227,new,Porsche Carrera 2025,2025,0 KM,Automatic,Gas,"14,500,000 EGP",NaN,Porsche,Carrera,https://eg.hatla2ee.com/en/new-car/porsche/car...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:34:12
1835,250,new,Nissan Juke 2026,2026,0 KM,Automatic,Gas,"1,090,000 EGP",NaN,Nissan,Juke,https://eg.hatla2ee.com/en/new-car/nissan/juke...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:41:16
2008,284,new,MG ZS 2026,2026,0 KM,Automatic,Gas,"1,150,000 EGP",NaN,MG,ZS,https://eg.hatla2ee.com/en/new-car/moris-garag...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:51:16
2069,294,new,Mercedes G63 2025,2025,0 KM,Automatic,Gas,"17,500,000 EGP",NaN,Mercedes,G63,https://eg.hatla2ee.com/en/new-car/mercedes/me...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 15:54:16
2231,326,new,Nissan Sentra 2026,2026,0 KM,Automatic,Gas,"1,040,000 EGP",NaN,Nissan,Sentra,https://eg.hatla2ee.com/en/new-car/nissan/sent...,https://legion-images.hatla2ee.com/listing_ima...,2026-04-30 16:03:25